[terminal]
vt = 1

[default_session]
command = "tuigreet --time --time-format '[ %A | %F | %I:%M %p ]' --power-shutdown 'systemctl poweroff' --power-reboot 'systemctl reboot' --user-menu --remember --asterisks --issue --theme 'border=magenta;text=cyan;prompt=green;time=red;action=blue;button=yellow;container=black;input=red' --cmd Hyprland"
user = "greeter"

[logging]
terminal = "syslog"
log_file = "/var/log/greetd.log"
